base_url: http://weixin.qnnsafe.com

#################
# subscription: #
#################
newly_subscribed: |
  您好！欢迎加入全能保险柜微信平台这个大家庭！
  需要了解什么呢？让我来帮您解答吧！
  您可在菜单栏快速点选功能，也可以直接输入数字指令！
  回复“0”获得更多帮助
  <a href="http://www.qnnsafe.com">点击进入全能官网</a> 

  全能保险柜，保险柜行业的全能冠军！
  缔造全能安全生活空间！ 
  全国客服热线：400-830-4555。

#######################
# find nearby stores: #
#######################

title_of_first_nearby_store: 打开地图查看各销售网点位置

# resolution: 80x80
default_nearby_store_image_url: http://www.qnnsafe.com/assets/images/qnn-icon-152.png

number_of_nearby_stores_to_list: 3

# test:
test:
  coord:
    lat: 22.849068
    lng: 113.216673
  nearby_store_name: 佛山大良专卖店
