newly_subscribed: |
  您好！欢迎加入全能保险柜微信平台这个大家庭！
  需要了解什么呢？让我来帮您解答吧！
  您可在菜单栏快速点选功能，也可以直接输入数字指令！
  回复“0”获得更多帮助
  <a href="http://www.qnnsafe.com">点击进入全能官网</a> 

  全能保险柜，保险柜行业的全能冠军！
  缔造全能安全生活空间！ 
  全国客服热线：400-830-4555。

unsubscribe: |
  再见！
